// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************
// ignore_for_file: constant_identifier_names

/// {@template assets_generator.assets_images_1_jpg.preview}
/// ![](d:\code\novel_flutter_bit\assets/images/1.jpg)
/// {@endtemplate}

/// {@template assets_generator.assets_images_300_1x_shots_so_png.preview}
/// ![](d:\code\novel_flutter_bit\assets/images/300_1x_shots_so.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_305shots_so_png.preview}
/// ![](d:\code\novel_flutter_bit\assets/images/305shots_so.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_488_1x_shots_so_png.preview}
/// ![](d:\code\novel_flutter_bit\assets/images/488_1x_shots_so.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_660_1x_shots_so_png.preview}
/// ![](d:\code\novel_flutter_bit\assets/images/660_1x_shots_so.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_970_1x_shots_so_png.preview}
/// ![](d:\code\novel_flutter_bit\assets/images/970_1x_shots_so.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_logo_png.preview}
/// ![](d:\code\novel_flutter_bit\assets/images/logo.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_logo1_jpg.preview}
/// ![](d:\code\novel_flutter_bit\assets/images/logo1.jpg)
/// {@endtemplate}

/// {@template assets_generator.assets_images_logo2_png.preview}
/// ![](d:\code\novel_flutter_bit\assets\images\logo2.png)
/// {@endtemplate}

/// {@template assets_generator.assets_svg_reload_1_svg.preview}
/// ![](d:\code\novel_flutter_bit\assets/svg/Reload 1.svg)
/// {@endtemplate}

/// {@template assets_generator.assets_svg_undo_up_svg.preview}
/// ![](d:\code\novel_flutter_bit\assets/svg/Undo_Up.svg)
/// {@endtemplate}

/// {@template assets_generator.assets_svg_empty_svg.preview}
/// ![](d:\code\novel_flutter_bit\assets/svg/empty.svg)
/// {@endtemplate}

/// {@template assets_generator.assets_svg_hot_svg.preview}
/// ![](d:\code\novel_flutter_bit\assets/svg/hot.svg)
/// {@endtemplate}

// ignore_for_file: camel_case_types, unused_element
class _ {}
