// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************
// ignore_for_file: constant_identifier_names

class Assets {
  const Assets._();

  /// {@macro assets_generator.assets_images_1_jpg.preview}
  static const String assets_images_1_jpg = 'assets/images/1.jpg';

  /// {@macro assets_generator.assets_images_logo_png.preview}
  static const String assets_images_logo_png = 'assets/images/logo.png';

  /// {@macro assets_generator.assets_images_logo1_jpg.preview}
  static const String assets_images_logo1_jpg = 'assets/images/logo1.jpg';

  /// {@macro assets_generator.assets_images_logo2_png.preview}
  static const String assets_images_logo2_png = 'assets/images/logo2.png';

  /// {@macro assets_generator.assets_images_refresh_gif.preview}
  static const String assets_images_refresh_gif = 'assets/images/refresh.gif';

  static const String assets_json_source_json = 'assets/json/source.json';

  /// {@macro assets_generator.assets_svg_reload_1_svg.preview}
  static const String assets_svg_reload_1_svg = 'assets/svg/Reload 1.svg';

  /// {@macro assets_generator.assets_svg_undo_up_svg.preview}
  static const String assets_svg_undo_up_svg = 'assets/svg/Undo_Up.svg';

  /// {@macro assets_generator.assets_svg_empty_svg.preview}
  static const String assets_svg_empty_svg = 'assets/svg/empty.svg';

  /// {@macro assets_generator.assets_svg_hot_svg.preview}
  static const String assets_svg_hot_svg = 'assets/svg/hot.svg';
}
